--
-- Script run when an upgrade of Dolibarr is done. Whatever is the Dolibarr version.
--

CREATE TABLE IF NOT EXISTS llx_fv_sefaz_profile (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    ref VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    environment VARCHAR(32) NOT NULL DEFAULT 'production',
    email VARCHAR(255),
    certificate_path VARCHAR(255),
    certificate_password VARCHAR(128),
    certificate_expire_at DATETIME,
    tax_regime VARCHAR(64),
    tax_regime_detail VARCHAR(64),
    csc_id VARCHAR(32),
    csc_token VARCHAR(80),
    webhook_secret VARCHAR(80),
    note_public TEXT,
    note_private TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, ref)
);

CREATE TABLE IF NOT EXISTS llx_fv_batch_export (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    ref VARCHAR(128),
    export_type VARCHAR(32),
    requested_at DATETIME,
    processed_at DATETIME,
    file_path VARCHAR(255),
    payload_json TEXT,
    error_message TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, ref)
);

CREATE TABLE IF NOT EXISTS llx_fv_focus_job (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    fk_sefaz_profile INTEGER,
    job_type VARCHAR(32),
    remote_id VARCHAR(64),
    attempt_count INTEGER DEFAULT 0,
    scheduled_for DATETIME,
    started_at DATETIME,
    finished_at DATETIME,
    payload_json TEXT,
    response_json TEXT,
    error_message TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, remote_id, job_type),
    FOREIGN KEY(fk_sefaz_profile) REFERENCES llx_fv_sefaz_profile(rowid)
);

CREATE TABLE IF NOT EXISTS llx_fv_nfe_out (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    ref VARCHAR(128),
    ref_ext VARCHAR(128),
    fk_soc INTEGER NOT NULL,
    fk_project INTEGER,
    fk_sefaz_profile INTEGER NOT NULL,
    fk_batch_export INTEGER,
    fk_focus_job INTEGER,
    doc_type VARCHAR(32) NOT NULL DEFAULT 'nfe',
    operation_type VARCHAR(32) DEFAULT 'sale',
    issue_at DATETIME,
    departure_at DATETIME,
    nfe_key VARCHAR(60),
    protocol_number VARCHAR(64),
    series VARCHAR(12),
    document_number VARCHAR(16),
    xml_path VARCHAR(255),
    pdf_path VARCHAR(255),
    total_products NUMERIC(24,8) DEFAULT 0,
    total_discount NUMERIC(24,8) DEFAULT 0,
    total_tax NUMERIC(24,8) DEFAULT 0,
    total_freight NUMERIC(24,8) DEFAULT 0,
    total_insurance NUMERIC(24,8) DEFAULT 0,
    total_other NUMERIC(24,8) DEFAULT 0,
    total_amount NUMERIC(24,8) DEFAULT 0,
    total_weight NUMERIC(24,8) DEFAULT 0,
    note_public TEXT,
    note_private TEXT,
    json_payload TEXT,
    json_response TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, nfe_key),
    FOREIGN KEY(fk_sefaz_profile) REFERENCES llx_fv_sefaz_profile(rowid),
    FOREIGN KEY(fk_batch_export) REFERENCES llx_fv_batch_export(rowid),
    FOREIGN KEY(fk_focus_job) REFERENCES llx_fv_focus_job(rowid)
);

CREATE TABLE IF NOT EXISTS llx_fv_nfe_out_line (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    fk_nfeout INTEGER NOT NULL,
    fk_product INTEGER,
    fk_unit INTEGER,
    rang INTEGER,
    ref VARCHAR(128),
    description TEXT,
    qty NUMERIC(24,8) DEFAULT 0,
    unit_price NUMERIC(24,8) DEFAULT 0,
    discount_percent NUMERIC(10,4) DEFAULT 0,
    discount_amount NUMERIC(24,8) DEFAULT 0,
    total_ht NUMERIC(24,8) DEFAULT 0,
    total_taxes NUMERIC(24,8) DEFAULT 0,
    total_ttc NUMERIC(24,8) DEFAULT 0,
    ncm VARCHAR(16),
    cfop VARCHAR(10),
    cest VARCHAR(10),
    icms_rate NUMERIC(10,4) DEFAULT 0,
    icms_amount NUMERIC(24,8) DEFAULT 0,
    ipi_rate NUMERIC(10,4) DEFAULT 0,
    ipi_amount NUMERIC(24,8) DEFAULT 0,
    pis_rate NUMERIC(10,4) DEFAULT 0,
    pis_amount NUMERIC(24,8) DEFAULT 0,
    cofins_rate NUMERIC(10,4) DEFAULT 0,
    cofins_amount NUMERIC(24,8) DEFAULT 0,
    issqn_rate NUMERIC(10,4) DEFAULT 0,
    issqn_amount NUMERIC(24,8) DEFAULT 0,
    created_at DATETIME,
    fk_user_create INTEGER,
    FOREIGN KEY(fk_nfeout) REFERENCES llx_fv_nfe_out(rowid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS llx_fv_nfe_event (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    fk_nfeout INTEGER NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    event_sequence INTEGER DEFAULT 1,
    protocol_number VARCHAR(64),
    received_at DATETIME,
    description TEXT,
    xml_path VARCHAR(255),
    json_payload TEXT,
    json_response TEXT,
    created_at DATETIME,
    fk_user_create INTEGER,
    FOREIGN KEY(fk_nfeout) REFERENCES llx_fv_nfe_out(rowid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS llx_fv_nfe_in (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    ref VARCHAR(128),
    ref_ext VARCHAR(128),
    fk_soc INTEGER NOT NULL,
    fk_project INTEGER,
    doc_type VARCHAR(32) NOT NULL DEFAULT 'nfe',
    operation_type VARCHAR(32),
    issue_at DATETIME,
    arrival_at DATETIME,
    nfe_key VARCHAR(60),
    xml_path VARCHAR(255),
    pdf_path VARCHAR(255),
    total_products NUMERIC(24,8) DEFAULT 0,
    total_tax NUMERIC(24,8) DEFAULT 0,
    total_amount NUMERIC(24,8) DEFAULT 0,
    note_public TEXT,
    note_private TEXT,
    json_payload TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, nfe_key)
);

CREATE TABLE IF NOT EXISTS llx_fv_mdfe (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    ref VARCHAR(128),
    fk_sefaz_profile INTEGER,
    fk_batch_export INTEGER,
    fk_focus_job INTEGER,
    issue_at DATETIME,
    mdfe_key VARCHAR(60),
    protocol_number VARCHAR(64),
    vehicle_plate VARCHAR(16),
    vehicle_rntrc VARCHAR(32),
    driver_name VARCHAR(128),
    driver_document VARCHAR(32),
    origin_city VARCHAR(128),
    origin_state VARCHAR(4),
    destination_city VARCHAR(128),
    destination_state VARCHAR(4),
    closure_at DATETIME,
    closure_city VARCHAR(128),
    closure_state VARCHAR(4),
    total_ctes INTEGER DEFAULT 0,
    total_weight NUMERIC(24,8) DEFAULT 0,
    total_value NUMERIC(24,8) DEFAULT 0,
    xml_path VARCHAR(255),
    pdf_path VARCHAR(255),
    json_payload TEXT,
    json_response TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    fk_user_create INTEGER,
    fk_user_modif INTEGER,
    UNIQUE(entity, mdfe_key),
    FOREIGN KEY(fk_sefaz_profile) REFERENCES llx_fv_sefaz_profile(rowid),
    FOREIGN KEY(fk_batch_export) REFERENCES llx_fv_batch_export(rowid),
    FOREIGN KEY(fk_focus_job) REFERENCES llx_fv_focus_job(rowid)
);

CREATE TABLE IF NOT EXISTS llx_fv_mdfe_nfe (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    fk_mdfe INTEGER NOT NULL,
    fk_nfeout INTEGER NOT NULL,
    created_at DATETIME,
    UNIQUE unique_fv_mdfe_nfe (fk_mdfe, fk_nfeout),
    INDEX idx_fv_mdfe_nfe_mdfe (fk_mdfe),
    INDEX idx_fv_mdfe_nfe_nfe (fk_nfeout),
    FOREIGN KEY(fk_mdfe) REFERENCES llx_fv_mdfe(rowid),
    FOREIGN KEY(fk_nfeout) REFERENCES llx_fv_nfe_out(rowid)
);

CREATE INDEX IF NOT EXISTS idx_fv_nfe_out_fk_soc ON llx_fv_nfe_out(fk_soc);
CREATE INDEX IF NOT EXISTS idx_fv_nfe_out_fk_profile ON llx_fv_nfe_out(fk_sefaz_profile);
CREATE INDEX IF NOT EXISTS idx_fv_nfe_out_line_fk ON llx_fv_nfe_out_line(fk_nfeout);
CREATE INDEX IF NOT EXISTS idx_fv_nfe_in_fk_soc ON llx_fv_nfe_in(fk_soc);
CREATE INDEX IF NOT EXISTS idx_fv_nfe_event_fk ON llx_fv_nfe_event(fk_nfeout);
CREATE INDEX IF NOT EXISTS idx_fv_mdfe_fk_profile ON llx_fv_mdfe(fk_sefaz_profile);
CREATE INDEX IF NOT EXISTS idx_fv_focus_job_profile ON llx_fv_focus_job(fk_sefaz_profile);
