-- SQL schema for FvFiscal module

CREATE TABLE llx_fv_partner_profile (
    rowid              BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity             INTEGER      NOT NULL DEFAULT 1,
    status             SMALLINT     NOT NULL DEFAULT 1,
    ref                VARCHAR(128) NOT NULL,
    fk_soc             INTEGER,
    settings_json      MEDIUMTEXT,
    remote_id          VARCHAR(64),
    remote_sync_date   DATETIME,
    created_at         DATETIME,
    updated_at         DATETIME,
    fk_user_create     INTEGER,
    fk_user_modif      INTEGER,
    UNIQUE KEY uk_fv_partner_profile_ref (entity, ref),
    KEY idx_fv_partner_profile_soc (fk_soc),
    KEY idx_fv_partner_profile_remote (remote_id)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_sefaz_profile (
    rowid                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity                  INTEGER      NOT NULL DEFAULT 1,
    status                  SMALLINT     NOT NULL DEFAULT 0,
    ref                     VARCHAR(128) NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    environment             VARCHAR(32)  NOT NULL DEFAULT 'production',
    email                   VARCHAR(255),
    certificate_path        VARCHAR(255),
    certificate_password    VARCHAR(128),
    certificate_expire_at   DATETIME,
    tax_regime              VARCHAR(64),
    tax_regime_detail       VARCHAR(64),
    csc_id                  VARCHAR(32),
    csc_token               VARCHAR(80),
    webhook_secret          VARCHAR(80),
    note_public             MEDIUMTEXT,
    note_private            MEDIUMTEXT,
    created_at              DATETIME,
    updated_at              DATETIME,
    fk_user_create          INTEGER,
    fk_user_modif           INTEGER,
    UNIQUE KEY uk_fv_sefaz_profile_ref (entity, ref)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_focus_job (
    rowid             BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity            INTEGER      NOT NULL DEFAULT 1,
    status            SMALLINT     NOT NULL DEFAULT 0,
    fk_sefaz_profile  INTEGER,
    job_type          VARCHAR(32),
    remote_id         VARCHAR(64),
    attempt_count     INTEGER      NOT NULL DEFAULT 0,
    scheduled_for     DATETIME,
    started_at        DATETIME,
    finished_at       DATETIME,
    payload_json      MEDIUMTEXT,
    response_json     MEDIUMTEXT,
    error_message     MEDIUMTEXT,
    created_at        DATETIME,
    updated_at        DATETIME,
    fk_user_create    INTEGER,
    fk_user_modif     INTEGER,
    KEY idx_fv_focus_job_sefaz (fk_sefaz_profile),
    KEY idx_fv_focus_job_remote (remote_id)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_batch (
    rowid               BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity              INTEGER      NOT NULL DEFAULT 1,
    status              SMALLINT     NOT NULL DEFAULT 0,
    ref                 VARCHAR(128) NOT NULL,
    fk_partner_profile  INTEGER,
    fk_sefaz_profile    INTEGER,
    fk_focus_job        INTEGER,
    batch_type          VARCHAR(32),
    remote_id           VARCHAR(64),
    remote_status       VARCHAR(32),
    scheduled_for       DATETIME,
    started_at          DATETIME,
    finished_at         DATETIME,
    settings_json       MEDIUMTEXT,
    created_at          DATETIME,
    updated_at          DATETIME,
    fk_user_create      INTEGER,
    fk_user_modif       INTEGER,
    UNIQUE KEY uk_fv_batch_ref (entity, ref),
    KEY idx_fv_batch_partner (fk_partner_profile),
    KEY idx_fv_batch_sefaz (fk_sefaz_profile),
    KEY idx_fv_batch_focus (fk_focus_job),
    KEY idx_fv_batch_remote (remote_id)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_batch_line (
    rowid            BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity           INTEGER      NOT NULL DEFAULT 1,
    fk_batch         INTEGER      NOT NULL,
    fk_parent_line   INTEGER,
    fk_origin        INTEGER,
    fk_origin_type   VARCHAR(64),
    line_type        VARCHAR(32),
    status           SMALLINT     NOT NULL DEFAULT 0,
    order_position   INTEGER      NOT NULL DEFAULT 0,
    payload_json     MEDIUMTEXT,
    response_json    MEDIUMTEXT,
    error_message    MEDIUMTEXT,
    scheduled_for    DATETIME,
    started_at       DATETIME,
    finished_at      DATETIME,
    created_at       DATETIME,
    updated_at       DATETIME,
    fk_user_create   INTEGER,
    KEY idx_fv_batch_line_batch (fk_batch),
    KEY idx_fv_batch_line_parent (fk_parent_line),
    KEY idx_fv_batch_line_origin (fk_origin, fk_origin_type)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_job (
    rowid             BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity            INTEGER      NOT NULL DEFAULT 1,
    status            SMALLINT     NOT NULL DEFAULT 0,
    ref               VARCHAR(128) NOT NULL,
    fk_batch          INTEGER,
    fk_batch_line     INTEGER,
    fk_focus_job      INTEGER,
    job_type          VARCHAR(32),
    job_payload       MEDIUMTEXT,
    job_response      MEDIUMTEXT,
    error_message     MEDIUMTEXT,
    scheduled_for     DATETIME,
    started_at        DATETIME,
    finished_at       DATETIME,
    attempt_count     INTEGER      NOT NULL DEFAULT 0,
    remote_id         VARCHAR(64),
    remote_status     VARCHAR(32),
    created_at        DATETIME,
    updated_at        DATETIME,
    fk_user_create    INTEGER,
    fk_user_modif     INTEGER,
    UNIQUE KEY uk_fv_job_ref (entity, ref),
    KEY idx_fv_job_batch (fk_batch),
    KEY idx_fv_job_batch_line (fk_batch_line),
    KEY idx_fv_job_focus (fk_focus_job),
    KEY idx_fv_job_remote (remote_id)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_job_line (
    rowid            BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity           INTEGER      NOT NULL DEFAULT 1,
    fk_job           INTEGER      NOT NULL,
    fk_parent_line   INTEGER,
    fk_batch_line    INTEGER,
    line_type        VARCHAR(32),
    status           SMALLINT     NOT NULL DEFAULT 0,
    payload_json     MEDIUMTEXT,
    response_json    MEDIUMTEXT,
    error_message    MEDIUMTEXT,
    order_position   INTEGER      NOT NULL DEFAULT 0,
    scheduled_for    DATETIME,
    started_at       DATETIME,
    finished_at      DATETIME,
    created_at       DATETIME,
    updated_at       DATETIME,
    fk_user_create   INTEGER,
    KEY idx_fv_job_line_job (fk_job),
    KEY idx_fv_job_line_parent (fk_parent_line),
    KEY idx_fv_job_line_batch_line (fk_batch_line)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;

CREATE TABLE llx_fv_batch_export (
    rowid            BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity           INTEGER      NOT NULL DEFAULT 1,
    status           SMALLINT     NOT NULL DEFAULT 0,
    ref              VARCHAR(128) NOT NULL,
    export_type      VARCHAR(32),
    requested_at     DATETIME,
    processed_at     DATETIME,
    file_path        VARCHAR(255),
    payload_json     MEDIUMTEXT,
    error_message    MEDIUMTEXT,
    created_at       DATETIME,
    updated_at       DATETIME,
    fk_user_create   INTEGER,
    fk_user_modif    INTEGER,
    UNIQUE KEY uk_fv_batch_export_ref (entity, ref)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4;
